version: '3'

services:
  web:
    build: .
    command: sh -c "./wait-for-mysql.sh db python manage.py migrate && python manage.py runserver 0:8000"
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
      - redis_server
    environment:
      - MYSQL_PASSWORD=password_password
      - MYSQL_DATABASE= demodb
      - MYSQL_USER=root

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password_password
      MYSQL_DATABASE: demodb

  redis_server:
    image: redis
